### ISSUE TITLE
I wanna run it in V100 GPU.

### ISSUE THREAD

**Issue by june9713** [MrBananaHuman/TextToBible#1]
안녕하세요~ 
이런 좋은 모델을 만들어 주셔서 감사드립니다 ㅎㅎ
혹시 V100 에서 돌리려면 어떤 부분을 수정해야 하는지 알수 있을까요?
Rtx2080 으로 돌렸을때랑 크게 차이가 없는것 같아서 수정을 해보려고 합니다.
혹시 도움이 될만한 부분이 있다면 알려주시면 감사하겠습니다.^^

**Comment by MrBananaHuman** [comment]
안녕하세요! 혹시 배치사이즈를 조절해보셨나요? :-)

**Comment by june9713** [comment]
네! 배치사이즈를 1024 이상 올리면 에러가 발생하더라구요^^ 1024에서는 큰 차이가 없었습니다. 트레이닝 하는데 몇일정도 걸리셨는지 알수 있을까요?^^

**Comment by MrBananaHuman** [comment]
헉 그렇군요 ㅠㅠㅠ 트레이닝은 일 단위까진 아니고 몇 시간?.. 안걸렸던 것 같아요! :-)
